Repository jdcarey128/Crate, pull requests merged in 2021-02, with the labels that each got.

#81 Backend setup
  code/api/package-lock.json
  code/api/package.json
  code/api/public/images/stock/default_profile.jpg
  code/api/src/config/database.json
  code/api/src/migrations/5-updateUsersTable.js
  code/api/src/migrations/6-order.js
  code/api/src/migrations/7-productDeliveries.js
  code/api/src/modules/crate/model.js
  code/api/src/modules/order/model.js
  code/api/src/modules/order/mutations.js
  code/api/src/modules/order/query.js
  code/api/src/modules/order/resolvers.js
  code/api/src/modules/order/types.js
  code/api/src/modules/productDelivery/model.js
  code/api/src/modules/productDelivery/types.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/types.js
  code/api/src/seeders/1-user.js
  code/api/src/seeders/4-orders.js
  code/api/src/seeders/5-productDeliveries.js
  code/api/src/setup/models.js
  code/api/src/setup/schema/mutations.js
  code/api/src/setup/schema/queries.js
  code/api/src/setup/test_helper.js
Labels: Back End

#82 Feature/profile form
  code/web/public/images/default-profile-image.jpg
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfileForm.js
  code/web/src/modules/user/api/actions.js
  code/web/src/setup/routes/user.js
Labels: Front End, epic: add image, epic: edit delivery date, epic: email, epic: personal description, epic: shipping address, features

#84 User login query
  code/api/src/modules/user/tests/queries.test.js
  code/api/src/setup/test_helper.js
Labels: Back End

#88 Fix/profile form state
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfileForm.js
Labels: Front End

#89 Update user be
  code/api/package-lock.json
  code/api/src/modules/order/mutations.js
  code/api/src/modules/order/query.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/tests/mutations.test.js
Labels: Back End

#90 Update/user be fe
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfileForm.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
Labels: Front End, epic: add image, epic: email, epic: personal description, epic: shipping address, features

#92 add orderUpdate mutation
  code/api/src/modules/order/mutations.js
  code/api/src/modules/order/resolvers.js
  code/api/src/modules/order/tests/mutations.test.js
  code/api/src/setup/schema/mutations.js
Labels: Back End

#94 Feature/test
  code/web/cypress.json
  code/web/cypress/fixtures/example.json
  code/web/cypress/integration/App.spec.js
  code/web/cypress/integration/examples/actions.spec.js
  code/web/cypress/integration/examples/aliasing.spec.js
  code/web/cypress/integration/examples/assertions.spec.js
  code/web/cypress/integration/examples/connectors.spec.js
  code/web/cypress/integration/examples/cookies.spec.js
  code/web/cypress/integration/examples/cypress_api.spec.js
  code/web/cypress/integration/examples/files.spec.js
  code/web/cypress/integration/examples/local_storage.spec.js
  code/web/cypress/integration/examples/location.spec.js
  code/web/cypress/integration/examples/misc.spec.js
  code/web/cypress/integration/examples/navigation.spec.js
  code/web/cypress/integration/examples/network_requests.spec.js
  code/web/cypress/integration/examples/querying.spec.js
  code/web/cypress/integration/examples/spies_stubs_clocks.spec.js
  code/web/cypress/integration/examples/traversal.spec.js
  code/web/cypress/integration/examples/utilities.spec.js
  code/web/cypress/integration/examples/viewport.spec.js
  code/web/cypress/integration/examples/waiting.spec.js
  code/web/cypress/integration/examples/window.spec.js
  code/web/cypress/plugins/index.js
  code/web/cypress/support/commands.js
  code/web/cypress/support/index.js
  code/web/package.json
  code/web/src/modules/user/ProfileForm.js
Labels: testing

#95 Feature/orders
  code/api/package-lock.json
  code/package-lock.json
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/common/header/Header.js
  code/web/src/modules/user/OrderCard.js
  code/web/src/modules/user/Orders.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/ProfileForm.js
  code/web/src/modules/user/api/actions.js
  code/web/src/setup/routes/user.js
Labels: Back End, Front End, epic: edit delivery date, features
